version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  image-processing-service:
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  vlm-solution-service:
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  iot-localization-service:
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
