version: '3.8'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  image-processing-service:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./image-processing-service:/app:ro
      - ./image-processing-service/uploads:/app/uploads
      - ./image-processing-service/weights:/app/weights
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--reload"]

  vlm-solution-service:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./vlm-solution-service/backend:/app:ro
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--reload"]

  iot-localization-service:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./iot-localization-service/backend:/app:ro

  uhi-simulation-service:
    environment:
      - NODE_ENV=development
      - PORT=4200
    volumes:
      - ./uhi-simulation-service/backend:/app:ro
      - ./uhi-simulation-service/backend/uploads:/app/uploads
      - ./uhi-simulation-service/backend/results:/app/results
    command: ["npm", "run", "dev"]
